apiVersion: v1
kind: Pod  
metadata:
  name: network-debug-advanced
  namespace: default
  labels:
    app: network-debug-advanced
spec:
  restartPolicy: Never
  containers:
  - name: netdebug-advanced
    image: nicolaka/netshoot:latest
    command: ["/bin/bash"]
    args:
    - -c
    - |
      echo "=== Advanced Network Debug ==="
      echo "Timestamp: Sun Sep 28 08:27:51 UTC 2025"
      echo
      
      echo "=== System Info ==="
      uname -a
      echo
      
      echo "=== DNS Deep Dive ==="
      echo "Testing DNS with dig:"
      dig google.com
      echo
      dig @8.8.8.8 pypi.org
      echo
      
      echo "=== Curl Tests ==="
      URLS=("https://pypi.org/simple/" "https://files.pythonhosted.org" "https://huggingface.co")
      
      for url in ""; do
        echo "Testing: "
        curl -v --connect-timeout 10 --max-time 30 "" 2>&1 | head -20
        echo "---"
      done
      
      echo "=== Network Tools Available ==="
      which nslookup dig curl wget nc nmap traceroute mtr
      echo
      
      echo "=== Traceroute Test ==="
      traceroute -m 10 8.8.8.8 || echo "Traceroute failed"
      echo
      
      echo "=== Container staying alive for debugging ==="
      echo "Use: kubectl exec -it network-debug-advanced -- /bin/bash"
      sleep 6000
    resources:
      requests:
        cpu: "100m" 
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
